# docker run -v ${PWD}/data/:/data/ tp
version: "3.8"

services:

  frontend:
    build: frontend/
    ports:
      - 80:80
    networks:
      - backend
      - proxy
    restart: on-failure

  recorder:
    build: recorder/
    volumes:
      - ./data:/data
    networks:
      - backend
    restart: on-failure

  tilecanoe:
    build: tilecanoe/
    volumes:
      - ./data:/data
    networks:
      - backend
    restart: on-failure

networks:
  backend:
  proxy:
    external: true
