version: "2.4"

services:

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - backend
      - reverse-proxy
    ports:
      - "80:80"
    restart: on-failure

  recorder:
    container_name: recorder
    build: ./recorder
    networks:
      - backend
    volumes:
      - ./data:/data
    restart: on-failure

  tilecanoe:
    container_name: tilecanoe
    build: ./tilecanoe
    networks:
      - backend
    volumes:
      - ./data:/data
    restart: on-failure

networks:
  backend:
  reverse-proxy:
    external: true
