version: "2.4"

services:

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - backend
      - nginx-proxy
    ports:
      - "8080:80"
    environment:
      VIRTUAL_HOST: map.dougbarrett.nz
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: map.dougbarrett.nz
    restart: on-failure

  recorder:
    container_name: recorder
    build: ./recorder
    networks:
      - backend
    volumes:
      - ./data:/data
    restart: on-failure

  tilecanoe:
    container_name: tilecanoe
    build: ./tilecanoe
    networks:
      - backend
    volumes:
      - ./data:/data
    restart: on-failure

networks:
  backend:
  nginx-proxy:
    external: true
